import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export async function generateProductImage(
  imageBase64: string,
  imageMimeType: string,
  prompt: string
): Promise<string> {
  // Use Gemini 2.0 Flash with image generation capability
  const model = genAI.getGenerativeModel({
    model: 'gemini-2.0-flash-exp',
    generationConfig: {
      // @ts-ignore - responseModalities is supported but not yet in types
      responseModalities: ['image', 'text'],
    },
  });

  const result = await model.generateContent([
    {
      inlineData: {
        data: imageBase64,
        mimeType: imageMimeType as 'image/jpeg' | 'image/png' | 'image/webp',
      },
    },
    {
      text: `You are a professional product photographer. Transform this product image into a new professional photo with this exact style and setting: ${prompt}
      
      IMPORTANT: Keep the product EXACTLY as it is (same product, same design, same colors). Only change the background and environment. The product must be clearly visible and professionally lit. Output a high-quality photorealistic image.`,
    },
  ]);

  const response = result.response;
  
  // Extract image from response
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData?.mimeType?.startsWith('image/')) {
      return part.inlineData.data; // base64 string
    }
  }

  throw new Error('No image was generated by Gemini');
}
